apiVersion: v1
kind: Service
metadata:
  name: test-spring-boot-backend-service
spec:
  selector:
    app: fake-spring-boot-backend
    purpose: mock-service
  ports:
    - port: 8080 # Port of this service
      targetPort: 8080 # Port of target node